compiler = clang++
linkflags = -lSDL2
files = main.cpp
compilerflags = -O2
outfile = gl_template


build: $(files) MakeFile
	$(compiler) files -o $(outfile) $(linkflags) $(compilerflags)

run : build
	$(outfile)

clean : 
	rm $(outfile)